name: Deploy MkDocs

# 触发条件：当主分支有代码推送且涉及文档文件时运行
on:
  push:
    branches:
      - wanxiang
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/deploy-docs.yml'
# 权限设置：允许机器人写入 gh-pages 分支
permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: 配置 Python 环境
        uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - name: 缓存提速配置
        run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV 

      - name: 设置 MkDocs 缓存
        uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: 安装依赖环境
        run: |
          pip install mkdocs-material
          # 如果你使用了其他插件，比如代码片段插件或中文搜索插件，也需要在这里 install，例如：
          # pip install pymdown-extensions

      - name: 自动编译并发布到 GitHub Pages
        run: mkdocs gh-deploy --force